language: node_js
node_js:
  - '7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - git reset --hard
  - npm run gulp-task publish-coverage
  - npm run gulp-task jsdoc
  - eval "$(ssh-agent -s)" #start the ssh agent
  - git config user.email "ahmedghoneim92@gmail.com"
  - git config user.name "Ahmed Ghoneim"
  - git remote add deploy git@github.com:aghoneim92/bpm.git
  - rm -rvf docs
  - mkdir docs
  - mv jsdoc docs
  - mv coverage docs
  - git add -f docs
  - git checkout -b gh-pages
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - npm run gulp-task git-push
  - npm run gulp-task npm-publish #if master and new version
